version: "3.8"
services:
  localstack:
    image: "localstack/localstack:latest"
    container_name: "localstack"
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=local
      - USE_HTTP=true
      - DEBUG=1