version: "3.8"
services:
  localstack:
    image: "localstack/localstack:latest"
    container_name: "localstack"
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=local
      - USE_HTTP=true
      - DEBUG=1
  postgres:
    image: postgres:latest
    container_name: localstack-app-pgsql
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5439:5432