#spring:
#    datasource:
#        username: "test"
#        password: "test"
#        url: "jdbc:postgresql://127.0.0.1:5432/test"
##        hikari:
##            connection-timeout: 2000 #ms
##            maximum-pool-size: 5
##            initialize: true
#    jpa:
#        hibernate:
#            ddl-auto : "create-drop"
#            properties:
#                hibernate:
#                    dialect : org.hibernate.dialect.PostgresDialect
