aws:
  endpoint: http://localhost:4566
  region: eu-central-1
  bucketName: cars-storage
  accessKeyId: local
  accessKeySecret: local

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5439/test
    username: test
    password: test
    initialize: true
  jpa:
    hibernate:
      ddl-auto : create